export const BIND_ACCOUNT_REQUEST = 'PRO/BIND_ACCOUNT_REQUEST';
export const BIND_ACCOUNT_SUCCESS = 'PRO/BIND_ACCOUNT_SUCCESS';
export const BIND_ACCOUNT_FAILURE = 'PRO/BIND_ACCOUNT_FAILURE';

export const UPDATE_BOUND_REQUEST = 'PRO/UPDATE_BOUND_REQUEST';
export const UPDATE_BOUND_SUCCESS = 'PRO/UPDATE_BOUND_SUCCESS';
export const UPDATE_BOUND_FAILURE = 'PRO/UPDATE_BOUND_FAILURE';

export const DELETE_BOUND_REQUEST = 'PRO/DELETE_BOUND_REQUEST';
export const DELETE_BOUND_SUCCESS = 'PRO/DELETE_BOUND_SUCCESS';
export const DELETE_BOUND_FAILURE = 'PRO/DELETE_BOUND_FAILURE';

export const GET_BOUND_REQUEST = 'PRO/GET_BOUND_REQUEST';
export const GET_BOUND_SUCCESS = 'PRO/GET_BOUND_SUCCESS';
export const GET_BOUND_FAILURE = 'PRO/GET_BOUND_FAILURE';

export const GET_KEYSTORE_REQUEST = 'PRO/GET_KEYSTORE_REQUEST';
export const GET_KEYSTORE_SUCCESS = 'PRO/GET_KEYSTORE_SUCCESS';
export const GET_KEYSTORE_FAILURE = 'PRO/GET_KEYSTORE_FAILURE';

export const CREATE_ACCOUNT_BY_SYSTEM_DIALOG_OPEN = 'PRO/CREATE_ACCOUNT_BY_SYSTEM_DIALOG_OPEN';
export const CREATE_ACCOUNT_BY_SYSTEM_DIALOG_CLOSE = 'PRO/CREATE_ACCOUNT_BY_SYSTEM_DIALOG_CLOSE';
export const CREATE_ACCOUNT_BY_SYSTEM_TX_REQUEST = 'PRO/CREATE_ACCOUNT_BY_SYSTEM_TX_REQUEST';
export const CREATE_ACCOUNT_BY_SYSTEM_TX_SUCCESS = 'PRO/CREATE_ACCOUNT_BY_SYSTEM_TX_SUCCESS';
export const CREATE_ACCOUNT_BY_SYSTEM_TX_FAILURE = 'PRO/CREATE_ACCOUNT_BY_SYSTEM_FTX_AILURE';

export const CREATE_ACCOUNT_BY_SELF_DIALOG_OPEN = 'PRO/CREATE_ACCOUNT_BY_SELF_DIALOG_OPEN';
export const CREATE_ACCOUNT_BY_SELF_DIALOG_CLOSE = 'PRO/CREATE_ACCOUNT_BY_SELF_DIALOG_CLOSE';

export const GET_ACCOUNT_INFO_REQUEST = 'PRO/GET_ACCOUNT_INFO_REQUEST';
export const GET_ACCOUNT_INFO_SUCCESS = 'PRO/GET_ACCOUNT_INFO_SUCCESS';
export const GET_ACCOUNT_INFO_FAILURE = 'PRO/GET_ACCOUNT_INFO_FAILURE';

export const IMPORT_ACCOUNT_DIALOG_OPEN = 'PRO/IMPORT_ACCOUNTDIALOG_OPEN';
export const IMPORT_ACCOUNT_DIALOG_CLOSE = 'PRO/IMPORT_ACCOUNT_DIALOG_CLOSE';
export const IMPORT_ACCOUNT_REQUEST = 'PRO/IMPORT_ACCOUNT_REQUEST';
export const IMPORT_ACCOUNT_SUCCESS = 'PRO/IMPORT_ACCOUNT_SUCCESS';
export const IMPORT_ACCOUNT_FAILURE = 'PRO/IMPORT_ACCOUNT_FAILURE';

export const TRANSFER_DIALOG_OPEN = 'PRO/TRANSFER_DIALOG_OPEN';
export const TRANSFER_DIALOG_CLOSE = 'PRO/TRANSFER_DIALOG_CLOSE';
export const TRANSFER_REQUEST = 'PRO/TRANSFER_REQUEST';
export const TRANSFER_SUCCESS = 'PRO/TRANSFER_SUCCESS';
export const TRANSFER_FAILURE = 'PRO/TRANSFER_FAILURE';

export const UPDATE_PK_DIALOG_OPEN = 'PRO/UPDATE_PK_DIALOG_OPEN';
export const UPDATE_PK_DIALOG_CLOSE = 'PRO/UPDATE_PK_DIALOG_CLOSE';
export const UPDATE_PK_REQUEST = 'PRO/UPDATE_PK_REQUEST';
export const UPDATE_PK_SUCCESS = 'PRO/UPDATE_PK_SUCCESS';
export const UPDATE_PK_FAILURE = 'PRO/UPDATE_PK_FAILURE';

export const RPC_REQUEST_FAILURE = 'PRO/RPC_REQUEST_FAILURE';

export const CLOSE_FAIL_DIALOG = 'PRO/CLOSE_FAIL_DIALOG';
