export const LATEST_BLOCK_REQUEST = 'PRO/LATEST_BLOCK_REQUEST';
export const LATEST_BLOCK_SUCCESS = 'PRO/LATEST_BLOCK_SUCCESS';
export const LATEST_BLOCK_FAILURE = 'PRO/LATEST_BLOCK_FAILURE';
export const TRANSACTION_NUM_REQUEST = 'PRO/TRANSACTION_NUM_REQUEST';
export const TRANSACTION_NUM_SUCCESS = 'PRO/TRANSACTION_NUM_SUCCESS';
export const TRANSACTION_NUM_FAILURE = 'PRO/TRANSACTION_NUM_FAILURE';
